### ISSUE TITLE
Upgrade ENet-CSharp to 2.4.7

### ISSUE THREAD

**Issue by Ahmed310** [JohannesDeml/ENetUnityMobile#4]
would be nice if you upgrade the plugin to the latest release.

I tried building for android and got following error

MINGW64 ~/Downloads/ENet-CSharp-master/ENet-CSharp-master/Source/Native
$ ndk-build
/c/Program Files/Unity/Editor/2020.1.6f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK/build/ndk-build: line 41: cd: too many arguments
ERROR: Cannot find 'make' program. Please install Cygwin make package
or define the GNUMAKE variable to point to it.

**Comment by JohannesDeml** [comment]
Hi @Ahmed310,

thanks for reaching out. The requirement of make (for windows Cygwin) was missing in the build steps. I added this steop in the documentation and created a new release for version 2.4.7. You can download the prebuilt libraries here: https://github.com/JohannesDeml/ENetUnityMobile/releases/tag/2.4.7

I hope that fixes your problem.

**Comment by Ahmed310** [comment]
Thanks for the quick reply

**Comment by Ahmed310** [comment]
while running the latest sample on Android getting this exception

06-01 01:24:46.382  4213  4237 E Unity   : InvalidOperationException: Incompatatible version
06-01 01:24:46.382  4213  4237 E Unity   :   at ENet.Library.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
06-01 01:24:46.382  4213  4237 E Unity   :   at Supyrb.ENetClient..ctor () [0x00000] in <00000000000000000000000000000000>:0 
06-01 01:24:46.382  4213  4237 E Unity   :   at Supyrb.ExampleEchoClient.Start () [0x00000] in <00000000000000000000000000000000>:0 

from ENet.cs

		public static bool Initialize() {
			if (Native.enet_linked_version() != version)
				throw new InvalidOperationException("Incompatatible version");

			return Native.enet_initialize() == 0;
		}
version miss match

**Comment by JohannesDeml** [comment]
I found the problem: Needed to remove the generated obj folder in order to recompile the libraries. Redownload the packages from the 2.4.7 release, should work now.

**Comment by Ahmed310** [comment]
Perfect!  Its working now, btw appreciate quick responses

**Comment by JohannesDeml** [comment]
Great, thanks for the confirmation and the report!

**Comment by Ahmed310** [comment]
@JohannesDeml there is a new Update ENet-CSharp 2.4.8. It would be great if you update it to latest version

**Comment by JohannesDeml** [comment]
Aloha!
Thanks for letting me know. I updated the project to the newest tech stack: https://github.com/JohannesDeml/ENetUnityMobile/releases/tag/2.4.8

Next time please create another issue instead of using an already fnished one.

**Comment by Ahmed310** [comment]
Awesome thanks for the quick update.

I will next time
